// <auto-generated />
using GalacticEmpire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalacticEmpire.Migrations
{
    [DbContext(typeof(GalacticEmpireContext))]
    partial class GalacticEmpireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalacticEmpire.Models.Entities.Habitant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPlanetOfOrigin")
                        .HasColumnType("int")
                        .HasColumnName("IdPlanet");

                    b.Property<int>("IdSpecie")
                        .HasColumnType("int")
                        .HasColumnName("IdSpecie");

                    b.Property<bool>("IsRebel")
                        .HasColumnType("bit")
                        .HasColumnName("IsRebel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Habitants");
                });

            modelBuilder.Entity("GalacticEmpire.Models.Entities.Planet", b =>
                {
                    b.Property<int>("IdPlanet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPlanet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanet"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("IdPlanet");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("GalacticEmpire.Models.Entities.Specie", b =>
                {
                    b.Property<int>("IdSpecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSpecie");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpecie"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("IdSpecie");

                    b.ToTable("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
